/**
 * The wire. DESIGN.md §3 is the contract; this file is that contract, executable.
 *
 * Seven events, discriminated on `t`, every one of them carrying `v`. Three of the
 * rules around them are structural here rather than advisory, because a rule a reviewer
 * has to remember is a rule that eventually ships broken:
 *
 *   - **Identity comes from the transport, never the payload** (CLAUDE.md §2.8). No
 *     event in this file has a sender field. A peer cannot lie about who it is because
 *     the schema gives it nowhere to write the lie; `receiveEvent` pairs the parsed
 *     event with the peer id the transport reported and that is the only `from` there
 *     is. `protocol.test.ts` asserts the absence, so adding one fails a test, and
 *     `identityClaimsIn` names the attempt in the log rather than filing a peer trying
 *     to act as someone else under "unrecognized key" (#41).
 *   - **Validate outbound and inbound, both, even single-player** (CLAUDE.md §2.7).
 *     `encodeEvent` runs the same union `parseEvent` does. Outbound it catches our own
 *     bug before a peer sees it; inbound it is the wall.
 *   - **Version mismatches reject outright** (DESIGN.md §3). There is no negotiation
 *     and no partial read. The version is checked before the union so the rejection can
 *     say *which* two versions disagreed — "a peer is running Lantern protocol 2" is
 *     something a user can act on, and "invalid literal at v" is not.
 *
 * 🚫 Nothing here adjudicates. A `request` is a message, not an effect: the owning
 * client decides what to do with it (PRD.md principle 2, and principle 3 — the DM's
 * authority is modelled, never enforced).
 */

import * as z from 'zod';
import {
  MAX_AC,
  MAX_CHARACTER_LEVEL,
  MAX_CHARACTER_NAME_LENGTH,
  MAX_CONDITIONS,
  MAX_DICE_PER_ROLL,
  MAX_DIE_SIDES,
  MAX_LUCK,
  MAX_NAME_LENGTH,
  MAX_PACK_CHUNK_BYTES,
  MAX_PACK_CHUNKS,
  MAX_ROLL_MODIFIER,
  MAX_TEXT_LENGTH,
  MAX_XP,
  MIN_CHARACTER_LEVEL,
  MIN_DIE_SIDES,
  PROTOCOL_VERSION,
} from '../constants';
import { Condition, HitPoints, PackId, Ref, RowId } from '../model/character';
import { formatProblems, validate, type Problem } from '../model/problems';
import { checkEventSize, isPeerId, type JsonValue, type PeerId } from './transport';

/** Zero is the floor of a count and the first index, not a rule of the game. */
const NONE = 0;

// ---------------------------------------------------------------------------
// The envelope
// ---------------------------------------------------------------------------

/**
 * Spread into every event rather than written seven times. A branch that forgot `v`
 * would be a branch that crosses a version boundary silently, which is the one failure
 * DESIGN.md §3 says must never be quiet.
 */
const envelope = { v: z.literal(PROTOCOL_VERSION) } as const;

/**
 * An event's own identity, generated by whoever sent it — a roll in the feed, a request
 * waiting on an answer. Same pattern and same bound as a row id on a sheet, because it
 * is used for the same job: a React key, and a name for a thing to refer back to.
 *
 * 🚫 Not a peer id. Nothing in this file identifies a *sender*.
 */
export const EventId = RowId;
export type EventId = z.infer<typeof EventId>;

/** Wall-clock milliseconds, as the sender reports them. See `HelloEvent.joinedAt`. */
export const Timestamp = z.int().min(NONE);
export type Timestamp = z.infer<typeof Timestamp>;

// ---------------------------------------------------------------------------
// The public projection. DESIGN.md §2.
// ---------------------------------------------------------------------------

/**
 * Everything one peer knows about another, and nothing else. Gold, journal, quests,
 * gear, spells and notes are not encrypted and sent — they are **not sent**.
 *
 * There is no `id` here, and its absence is the design. DESIGN.md §2 describes the
 * assembled type as carrying one; it is added on receipt from the peer id the transport
 * reports (`ReceivedEvent`), so a peer has no field in which to claim to be someone
 * else. `ancestry` and `className` are strings rather than refs because the peer
 * reading them may not have the pack that names them, and a party view showing a blank
 * where a class should be is worse than showing a word.
 */
export const PublicCharacter = z.strictObject({
  name: z.string().max(MAX_CHARACTER_NAME_LENGTH),
  ancestry: z.string().max(MAX_NAME_LENGTH),
  className: z.string().max(MAX_NAME_LENGTH),
  level: z.int().min(MIN_CHARACTER_LEVEL).max(MAX_CHARACTER_LEVEL),
  hp: HitPoints,
  /** Derived on the sender's machine (CLAUDE.md §4) and bounded here as a peer's claim. */
  ac: z.int().min(NONE).max(MAX_AC),
  conditions: z.array(Condition).max(MAX_CONDITIONS),
  carryingLight: z.boolean(),
  luck: z.int().min(NONE).max(MAX_LUCK),
});
export type PublicCharacter = z.infer<typeof PublicCharacter>;

// ---------------------------------------------------------------------------
// Dice. DESIGN.md §4.
// ---------------------------------------------------------------------------

/**
 * One die and what it showed. `value` is checked against this die's own `sides`, not
 * against the largest die there is: a d6 that reports a 9 is a peer that is lying or
 * broken, and either way it is not a roll.
 */
export const DieResult = z
  .strictObject({
    sides: z.int().min(MIN_DIE_SIDES).max(MAX_DIE_SIDES),
    value: z.int().min(1).max(MAX_DIE_SIDES),
  })
  .refine((die) => die.value <= die.sides, {
    error: 'value must be no larger than the die has sides',
    path: ['value'],
  });
export type DieResult = z.infer<typeof DieResult>;

/**
 * Who a roll is for. DESIGN.md §4 makes the third case absolute: **a `just-me` roll
 * must not broadcast its numbers at all**, because sending them and hiding them client
 * side is not secret. So the wire cannot express one — the rule lives in the type
 * rather than in a reviewer's memory, and a `just-me` roll simply never reaches this
 * file. The local three-value control belongs to the dice UI (Phase 3).
 */
export const SharedVisibility = z.enum(['everyone', 'dm-only']);
export type SharedVisibility = z.infer<typeof SharedVisibility>;

/**
 * A table roll is a roll plus a lookup, and the app never parses the result — it prints
 * the row (DESIGN.md §4). `text` is a pack's own words travelling between peers who
 * both chose to load it; nothing in this repo ships any.
 */
export const TableLookup = z.strictObject({
  table: Ref,
  row: z.string().max(MAX_TEXT_LENGTH),
});
export type TableLookup = z.infer<typeof TableLookup>;

// ---------------------------------------------------------------------------
// Requests. DESIGN.md §2 — one writer per character.
// ---------------------------------------------------------------------------

/**
 * What a request may ask to change. Deliberately short: these are the numbers a DM
 * moves out loud at a table. Anything an effects engine would want is out of scope
 * permanently (PRD.md §4).
 */
export const AdjustableField = z.enum(['hp', 'luck', 'xp']);
export type AdjustableField = z.infer<typeof AdjustableField>;

/**
 * The three shapes a request comes in — a question that wants a yes or no, a number to
 * move, a condition to add or drop. Discriminated on `kind` so Phase 6 can add a fourth
 * without any of the three growing an optional field that only sometimes means anything.
 *
 * `delta` is bounded by the widest of the three fields it may apply to; the client that
 * owns the sheet clamps it to that field's real bound when it applies it. Bounding it
 * per field here would mean trusting `field` to decide how much to trust `delta`.
 */
export const RequestBody = z.discriminatedUnion('kind', [
  z.strictObject({
    kind: z.literal('ask'),
    text: z.string().min(1).max(MAX_TEXT_LENGTH),
  }),
  z.strictObject({
    kind: z.literal('adjust'),
    field: AdjustableField,
    delta: z.int().min(-MAX_XP).max(MAX_XP),
    note: z.string().max(MAX_TEXT_LENGTH),
  }),
  z.strictObject({
    kind: z.literal('condition'),
    condition: Condition,
    add: z.boolean(),
    note: z.string().max(MAX_TEXT_LENGTH),
  }),
]);
export type RequestBody = z.infer<typeof RequestBody>;

/**
 * An answer is a record and a courtesy, never a gate (PRD.md principle 3). Nothing in
 * the app is unlocked by an `allowed`, and refusing does not stop anyone — every client
 * runs its own code, and the UI must never imply otherwise.
 */
export const Decision = z.enum(['allowed', 'refused']);
export type Decision = z.infer<typeof Decision>;

// ---------------------------------------------------------------------------
// The scene. DESIGN.md §6.
// ---------------------------------------------------------------------------

/** How hard the room leans on the torch. Room-wide, so the table agrees. */
export const TorchMode = z.enum(['dim', 'bar', 'off']);
export type TorchMode = z.infer<typeof TorchMode>;

// ---------------------------------------------------------------------------
// The seven events. DESIGN.md §3.
// ---------------------------------------------------------------------------

/**
 * Broadcast on arrival. `joinedAt` decides the host — longest present, ties broken by
 * peer id — and a peer can lie about it to claim the chair. DESIGN.md §3 accepts that
 * knowingly: the host is a cosmetic role with no authority over anyone's dice, and a
 * consensus protocol would cost more than the chair is worth.
 */
export const HelloEvent = z.strictObject({
  ...envelope,
  t: z.literal('hello'),
  character: PublicCharacter,
  joinedAt: Timestamp,
});
export type HelloEvent = z.infer<typeof HelloEvent>;

/** The projection again, after something changed. Debounced by `BROADCAST_DEBOUNCE_MS`. */
export const StateEvent = z.strictObject({
  ...envelope,
  t: z.literal('state'),
  character: PublicCharacter,
});
export type StateEvent = z.infer<typeof StateEvent>;

/**
 * A roll and what it showed. There is no `total` — it is `dice` plus `modifier`, and a
 * derived value on the wire is a derived value stored (CLAUDE.md §4). Sending one would
 * mean either recomputing it and ignoring it, or trusting a number a peer chose.
 */
export const RollEvent = z.strictObject({
  ...envelope,
  t: z.literal('roll'),
  id: EventId,
  /** What was rolled, in the sender's words: `Longsword`, `Sneak`. Never rules text. */
  label: z.string().max(MAX_NAME_LENGTH),
  dice: z.array(DieResult).min(1).max(MAX_DICE_PER_ROLL),
  modifier: z.int().min(-MAX_ROLL_MODIFIER).max(MAX_ROLL_MODIFIER),
  visibility: SharedVisibility,
  /** Null for a free roll from the handle; a row for a table roll. */
  lookup: TableLookup.nullable(),
});
export type RollEvent = z.infer<typeof RollEvent>;

/**
 * Sent to one peer. There is no `to` field: the recipient is the peer the transport was
 * asked to send to, and a second copy of that inside the payload would be a second
 * chance for the two to disagree.
 */
export const RequestEvent = z.strictObject({
  ...envelope,
  t: z.literal('request'),
  id: EventId,
  body: RequestBody,
});
export type RequestEvent = z.infer<typeof RequestEvent>;

/** `requestId` names the request being answered, never a peer. */
export const ResponseEvent = z.strictObject({
  ...envelope,
  t: z.literal('response'),
  requestId: EventId,
  decision: Decision,
  note: z.string().max(MAX_TEXT_LENGTH),
});
export type ResponseEvent = z.infer<typeof ResponseEvent>;

/**
 * A pack, in pieces, to one peer. `chunk` is a slice of the pack's JSON as text; the
 * receiver concatenates `total` of them in `seq` order and hands the result to the pack
 * parser, which is the thing that decides whether it was a pack at all.
 *
 * 📌 `MAX_PACK_CHUNK_BYTES` bounds *characters* here, not bytes — a Zod string length is
 * a character count and one character can be four bytes on the wire. That is deliberate
 * and safe in this direction: the byte wall is `checkEventSize`, which has already run
 * by the time this schema sees anything.
 */
export const PackEvent = z
  .strictObject({
    ...envelope,
    t: z.literal('pack'),
    packId: PackId,
    /** Zero-based, so the last piece of a whole pack is `total - 1`. */
    seq: z.int().min(NONE).max(MAX_PACK_CHUNKS - 1),
    total: z.int().min(1).max(MAX_PACK_CHUNKS),
    chunk: z.string().max(MAX_PACK_CHUNK_BYTES),
  })
  .refine((event) => event.seq < event.total, {
    error: 'seq must be less than total',
    path: ['seq'],
  });
export type PackEvent = z.infer<typeof PackEvent>;

/** The DM sets where everyone is and how dark it is. Broadcast. */
export const SceneEvent = z.strictObject({
  ...envelope,
  t: z.literal('scene'),
  location: z.string().max(MAX_NAME_LENGTH),
  torch: TorchMode,
});
export type SceneEvent = z.infer<typeof SceneEvent>;

/**
 * Everything that may cross the wire. One Trystero action carries all of it
 * (`TRYSTERO_ACTION_NAMESPACE`) because `t` already discriminates it, and a second
 * dispatch layer would be a second place for the two to disagree.
 */
export const ProtocolEvent = z.discriminatedUnion('t', [
  HelloEvent,
  StateEvent,
  RollEvent,
  RequestEvent,
  ResponseEvent,
  PackEvent,
  SceneEvent,
]);
export type ProtocolEvent = z.infer<typeof ProtocolEvent>;

/** The discriminator's own type, so a `switch` over it can be checked for completeness. */
export type EventType = ProtocolEvent['t'];

// ---------------------------------------------------------------------------
// The boundary
// ---------------------------------------------------------------------------

/**
 * Why a payload was refused. Each kind is a different thing to tell the user, which is
 * the only reason to distinguish them: `version-mismatch` means update the tab,
 * `malformed` means a peer is broken, `too-large` means something ran away.
 *
 * Every one carries a finished sentence. DESIGN.md §3 requires a version mismatch to be
 * *visible*, and a rejection the UI has to compose a sentence for is one the UI will
 * eventually show as `[object Object]`.
 */
export type ProtocolRejection =
  | { readonly kind: 'too-large'; readonly message: string }
  | {
      readonly kind: 'version-mismatch';
      readonly message: string;
      readonly theirs: number;
      readonly ours: number;
    }
  | {
      readonly kind: 'malformed';
      readonly message: string;
      readonly problems: readonly Problem[];
    };

export type ParseEventResult =
  | { readonly ok: true; readonly event: ProtocolEvent }
  | { readonly ok: false; readonly rejection: ProtocolRejection };

export type EncodeEventResult =
  | { readonly ok: true; readonly payload: JsonValue }
  | { readonly ok: false; readonly rejection: ProtocolRejection };

/**
 * A parsed event and who actually sent it. This is the only place a `from` exists, and
 * it holds the peer id the transport reported rather than anything the payload said —
 * CLAUDE.md §2.8, made unavoidable by the schemas having no such field to begin with.
 */
export type ReceivedEvent = {
  readonly from: PeerId;
  readonly event: ProtocolEvent;
};

export type ReceiveEventResult =
  | { readonly ok: true; readonly received: ReceivedEvent }
  | { readonly ok: false; readonly rejection: ProtocolRejection };

/**
 * Reads `v` and nothing else, off anything. Loose rather than strict on purpose: the
 * point is to answer "which protocol did whoever sent this think they were speaking",
 * from a payload that is by definition not one of ours.
 */
const Versioned = z.object({ v: z.number() });

/**
 * Key names a payload would have to use to name a sender. None of them is a field of
 * any event — the schemas are strict, so a payload carrying one is refused either way
 * (CLAUDE.md §2.8, DESIGN.md §3: there was never anywhere to write the lie).
 *
 * The list exists so the refusal can *say so*. A spoof attempt and a typo are both
 * "unrecognized key" to Zod, and they are not the same thing to the person reading the
 * log: one is a peer running an old build, the other is a peer trying to act as someone
 * else. Naming it costs one pass over a fixed list of seven strings.
 */
const SENDER_KEYS: readonly string[] = [
  'from',
  'sender',
  'senderId',
  'peer',
  'peerId',
  'author',
  'by',
];

/**
 * Inside `character`, `id` is a sender claim as well. DESIGN.md §2 — there is no `id`
 * on the wire; the party member's id is the peer id the transport reported, added on
 * receipt. A projection that arrives carrying one is claiming to be a seat.
 */
const CHARACTER_SENDER_KEYS: readonly string[] = ['id', ...SENDER_KEYS];

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function claimsIn(record: Record<string, unknown>, keys: readonly string[], prefix: string): string[] {
  return keys.filter((key) => Object.hasOwn(record, key)).map((key) => `${prefix}${key}`);
}

/**
 * Every place this payload tried to name its own sender. Empty for everything honest,
 * which is every event this app produces.
 *
 * 📌 Detection only. Nothing is stripped and nothing is rewritten: a payload that claims
 * a sender is refused whole, because a peer that edits the envelope is not a peer whose
 * remaining fields have earned a second look.
 */
export function identityClaimsIn(input: unknown): readonly string[] {
  if (!isRecord(input)) return [];

  const claims = claimsIn(input, SENDER_KEYS, '');
  const character = input['character'];

  return isRecord(character)
    ? [...claims, ...claimsIn(character, CHARACTER_SENDER_KEYS, 'character.')]
    : claims;
}

function malformed(problems: readonly Problem[]): ProtocolRejection {
  return {
    kind: 'malformed',
    message: `not a Lantern event:\n${formatProblems(problems)}`,
    problems,
  };
}

/**
 * Everything that must be true before an inbound payload is an event, in the order that
 * makes each rejection say the most useful thing:
 *
 *   1. **Size.** A megabyte of nonsense is dropped before Zod walks it.
 *   2. **Version.** Checked ahead of the union so the rejection can name both versions.
 *      DESIGN.md §3 — there is no negotiation, and a mismatch is never a near miss to
 *      be patched up.
 *   3. **Identity.** A payload naming its own sender is refused before its shape is
 *      considered, so the rejection says what it was rather than "unrecognized key".
 *      CLAUDE.md §2.8 — nothing a payload says about who sent it is ever read.
 *   4. **Shape.** The union, strict throughout, with every problem reported.
 *
 * Never throws. A payload that fails is a value describing the failure (CLAUDE.md §2.5).
 */
export function parseEvent(input: unknown): ParseEventResult {
  const size = checkEventSize(input);
  if (!size.ok) {
    if (size.error.kind === 'too-large') {
      return { ok: false, rejection: { kind: 'too-large', message: size.error.message } };
    }
    return { ok: false, rejection: malformed([{ path: '(root)', message: size.error.message }]) };
  }

  const versioned = Versioned.safeParse(input);
  if (versioned.success && versioned.data.v !== PROTOCOL_VERSION) {
    const theirs = versioned.data.v;
    return {
      ok: false,
      rejection: {
        kind: 'version-mismatch',
        theirs,
        ours: PROTOCOL_VERSION,
        message:
          `this peer speaks Lantern protocol ${theirs} and you speak ${PROTOCOL_VERSION}. ` +
          'There is no translation between them — both tabs need the same version of Lantern.',
      },
    };
  }

  const claims = identityClaimsIn(input);
  if (claims.length > 0) {
    return {
      ok: false,
      rejection: malformed(
        claims.map((claim) => ({
          path: claim,
          message:
            'a payload may not name its own sender — identity comes from the transport, ' +
            'so this event is refused rather than believed',
        })),
      ),
    };
  }

  const parsed = validate(ProtocolEvent, input);
  if (!parsed.ok) return { ok: false, rejection: malformed(parsed.problems) };

  return { ok: true, event: parsed.value };
}

/**
 * The same walls, on the way out (CLAUDE.md §2.7). It runs with one player at the table
 * and no room open, because the bug it catches is ours: an event assembled wrong is
 * found here, on the machine that can still be debugged, instead of on a peer's.
 */
export function encodeEvent(event: ProtocolEvent): EncodeEventResult {
  const parsed = validate(ProtocolEvent, event);
  if (!parsed.ok) return { ok: false, rejection: malformed(parsed.problems) };

  const size = checkEventSize(parsed.value);
  if (!size.ok) {
    if (size.error.kind === 'too-large') {
      return { ok: false, rejection: { kind: 'too-large', message: size.error.message } };
    }
    return { ok: false, rejection: malformed([{ path: '(root)', message: size.error.message }]) };
  }

  return { ok: true, payload: parsed.value };
}

/**
 * What `TransportHandlers.onMessage` hands upward, turned into an event and an author.
 * `from` is the transport's word and the payload has no say in it.
 *
 * This is the only function in the app that decides who sent something, and it takes
 * that from its first argument — the transport's — every time. There is no branch in
 * which a value out of `data` becomes a `from`, and the checks in `parseEvent` mean
 * there is nothing in `data` that could be mistaken for one.
 *
 * An unusable `from` is a refusal rather than an attribution to whatever was passed. It
 * cannot happen through the transport, which checks first, and that is the point: a
 * later caller that forgets loses the message instead of inventing a peer.
 */
export function receiveEvent(from: PeerId, data: unknown): ReceiveEventResult {
  if (!isPeerId(from)) {
    return {
      ok: false,
      rejection: malformed([
        {
          path: '(sender)',
          message: `the transport reported no usable peer id (${JSON.stringify(from)}), so this event cannot be attributed to anyone`,
        },
      ]),
    };
  }

  const parsed = parseEvent(data);
  if (!parsed.ok) return { ok: false, rejection: parsed.rejection };

  return { ok: true, received: { from, event: parsed.event } };
}

/** One line, for a log or for the lobby. Rejections are shown, never swallowed. */
export function describeRejection(rejection: ProtocolRejection): string {
  return `${rejection.kind}: ${rejection.message}`;
}
