/**
 * A pack as a file a DM picked off their disk. DATA-MODEL.md §1, §9.
 *
 * This is `state/core-pack.ts` with a file in front of it instead of a fetch, and the
 * same four steps in the same order: **bound, decode, parse, and never throw.** A pack
 * from a picker is hostile input in exactly the way a pack from a peer is — it may have
 * been written by hand, generated by a model, or not be a pack at all — so nothing here
 * trusts a field before the schema has seen it (CLAUDE.md §2.7).
 *
 * The size is checked twice on purpose, and the two checks are not the same check. A
 * `File.size` is what the browser says about a thing on disk, and it is read *before a
 * byte is decoded*, so an enormous file is refused rather than pulled into memory to be
 * refused. The decoded length is what we are actually holding. `character-file.ts` draws
 * the same distinction for the same reason (DATA-MODEL.md §12).
 *
 * There is no DOM here and no React. Picking the file is `ui/ContentScreen.tsx`.
 */

import { MAX_PACK_BYTES } from '../constants';
import type { Pack, PackProblem } from '../model/pack';
import { parsePack } from '../model/pack';
import { describeError } from './storage';

/** What the file picker offers by default. Both spellings: browsers disagree on which. */
export const PACK_FILE_ACCEPT = 'application/json,.json';

/** The path a problem takes when the fault is the file rather than a field inside it. */
const WHOLE_FILE = '(root)';

/**
 * What this module needs of a picked file: its name, its size, and its text. Structural
 * rather than the DOM `File` type, for the same reason `PickedFile` in
 * `character-file.ts` is — a test hands in an object, including one that throws on read,
 * so the failure path is exercised rather than assumed. A real `File` satisfies it.
 */
export type PickedPackFile = {
  readonly name: string;
  readonly size: number;
  text(): Promise<string>;
};

/** Errors are values at every boundary. CLAUDE.md §2.5. */
export type PackFileRead =
  | { readonly ok: true; readonly pack: Pack }
  | { readonly ok: false; readonly problems: readonly PackProblem[] };

const problem = (message: string): PackFileRead => ({
  ok: false,
  problems: [{ path: WHOLE_FILE, message }],
});

/**
 * Read a pack out of text. Bounded first, because the cap exists to stop a large file
 * being decoded at all; then decoded, then validated — each step reporting what it found
 * in DATA-MODEL.md §9's grammar rather than throwing it.
 */
export function fromPackFileText(text: string): PackFileRead {
  // A UTF-16 length never exceeds the byte count it encodes to, so this is the
  // conservative half of the bound `readPackFile` puts on the file itself.
  if (text.length > MAX_PACK_BYTES) {
    return problem(`expected at most ${MAX_PACK_BYTES} characters — got ${text.length} characters`);
  }

  let decoded: unknown;
  try {
    decoded = JSON.parse(text);
  } catch (error: unknown) {
    return problem(`expected JSON — ${describeError(error)}`);
  }

  return parsePack(decoded);
}

/**
 * Read a picked file. The size is checked before a byte is read, and a read that fails —
 * a file moved or unplugged between the picker and here — is a problem with a path like
 * any other rather than an exception nobody catches.
 */
export async function readPackFile(file: PickedPackFile): Promise<PackFileRead> {
  if (file.size > MAX_PACK_BYTES) {
    return problem(`expected at most ${MAX_PACK_BYTES} bytes — got ${file.size} bytes`);
  }

  let text: string;
  try {
    text = await file.text();
  } catch (error: unknown) {
    return problem(`the file could not be read — ${describeError(error)}`);
  }

  return fromPackFileText(text);
}
